version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "Dependency"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "Dependency"
      include: "scope"
