spring:
  security:
    saml2:
      relyingparty:
        registration:
          # somerelayingpartyname: # This decides on the callback url! https://<<DOMAIN>>/saml2/service-provider-metadata/<REGISTRATION_ID_HERE>
          # signing.credentials: &my-metadata
          #   - private-key-location: file:/opt/artemis/config/shibboleth-sp-key.pem
          #     certificate-location: file:/opt/artemis/config/shibboleth-sp-cert.crt
          # decryption.credentials: *my-metadata
          # assertingparty:
          #   metadata-uri: URL_TO_METADATA_HERE

news:
  # path to csv files containing (key, message) pairs
  csv-path: # Path to the csv files
  # One of http://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.Predefined.html
  csv-format: Default
  # The saml2 attribute used as key
  saml2-key: # the saml2 key to use as key in csv files
  mail-saml2-key: # the saml2 key to get a name (e.g., the mail address)

logging.level:
  org.springframework.security: WARN
  edu.kit: WARN
