spring:
  security:
    saml2:
      relyingparty:
        registration:
          # somerelayingpartyname: # This decides on the callback url!
          #   signing.credentials:
          #     - private-key-location: # file:path/to/private.key
          #       certificate-location: # file:path/to/certificate.crt
          #   identityprovider:
          #     metadata-uri: # https://../metadata.php

news:
  # path to csv files containing (key, message) pairs
  csv-path: # Path to the csv files
  # One of http://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.Predefined.html
  csv-format: Default
  # The saml2 attribute used as key
  saml2-key: # the saml2 key to use as key in csv files

logging.level:
  org.springframework.security: WARN
  edu.kit: WARN
